
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action newActionArticulo;
	private global::Gtk.Action editAction;
	private global::Gtk.Action deleteAction;
	private global::Gtk.Action findAction;
	private global::Gtk.Action refreshAction;
	private global::Gtk.Action newActionCategoria;
	private global::Gtk.Action editAction1;
	private global::Gtk.Action deleteAction1;
	private global::Gtk.Action refreshAction1;
	private global::Gtk.Action findAction1;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Notebook notebook;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Toolbar toolbar;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView treeViewArticulo;
	private global::Gtk.Label labelArticulo;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Toolbar toolbar2;
	private global::Gtk.ScrolledWindow scrolledwindow2;
	private global::Gtk.TreeView treeViewCategoria;
	private global::Gtk.Label labelCategoria;
	private global::Gtk.Label frame;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.newActionArticulo = new global::Gtk.Action ("newActionArticulo", null, null, "gtk-new");
		w1.Add (this.newActionArticulo, null);
		this.editAction = new global::Gtk.Action ("editAction", null, null, "gtk-edit");
		w1.Add (this.editAction, null);
		this.deleteAction = new global::Gtk.Action ("deleteAction", null, null, "gtk-delete");
		w1.Add (this.deleteAction, null);
		this.findAction = new global::Gtk.Action ("findAction", null, null, "gtk-find");
		w1.Add (this.findAction, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
		w1.Add (this.refreshAction, null);
		this.newActionCategoria = new global::Gtk.Action ("newActionCategoria", null, null, "gtk-new");
		w1.Add (this.newActionCategoria, null);
		this.editAction1 = new global::Gtk.Action ("editAction1", null, null, "gtk-edit");
		w1.Add (this.editAction1, null);
		this.deleteAction1 = new global::Gtk.Action ("deleteAction1", null, null, "gtk-delete");
		w1.Add (this.deleteAction1, null);
		this.refreshAction1 = new global::Gtk.Action ("refreshAction1", null, null, "gtk-refresh");
		w1.Add (this.refreshAction1, null);
		this.findAction1 = new global::Gtk.Action ("findAction1", null, null, "gtk-find");
		w1.Add (this.findAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'/></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook = new global::Gtk.Notebook ();
		this.notebook.CanFocus = true;
		this.notebook.Name = "notebook";
		this.notebook.CurrentPage = 0;
		// Container child notebook.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar'><toolitem name='newActionArticulo' action='newActionArticulo'/><toolitem name='editAction' action='editAction'/><toolitem name='deleteAction' action='deleteAction'/><toolitem name='refreshAction' action='refreshAction'/><toolitem name='findAction' action='findAction'/></toolbar></ui>");
		this.toolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar")));
		this.toolbar.Name = "toolbar";
		this.toolbar.ShowArrow = false;
		this.vbox2.Add (this.toolbar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.toolbar]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeViewArticulo = new global::Gtk.TreeView ();
		this.treeViewArticulo.CanFocus = true;
		this.treeViewArticulo.Name = "treeViewArticulo";
		this.GtkScrolledWindow.Add (this.treeViewArticulo);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
		w5.Position = 1;
		this.notebook.Add (this.vbox2);
		// Notebook tab
		this.labelArticulo = new global::Gtk.Label ();
		this.labelArticulo.Name = "labelArticulo";
		this.labelArticulo.LabelProp = global::Mono.Unix.Catalog.GetString ("Artículo");
		this.notebook.SetTabLabel (this.vbox2, this.labelArticulo);
		this.labelArticulo.ShowAll ();
		// Container child notebook.Gtk.Notebook+NotebookChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar2'><toolitem name='newActionCategoria' action='newActionCategoria'/><toolitem name='editAction1' action='editAction1'/><toolitem name='deleteAction1' action='deleteAction1'/><toolitem name='refreshAction1' action='refreshAction1'/><toolitem name='findAction1' action='findAction1'/></toolbar></ui>");
		this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
		this.toolbar2.Name = "toolbar2";
		this.toolbar2.ShowArrow = false;
		this.vbox4.Add (this.toolbar2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.toolbar2]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow2.CanFocus = true;
		this.scrolledwindow2.Name = "scrolledwindow2";
		this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow2.Gtk.Container+ContainerChild
		this.treeViewCategoria = new global::Gtk.TreeView ();
		this.treeViewCategoria.CanFocus = true;
		this.treeViewCategoria.Name = "treeViewCategoria";
		this.scrolledwindow2.Add (this.treeViewCategoria);
		this.vbox4.Add (this.scrolledwindow2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.scrolledwindow2]));
		w9.Position = 1;
		this.notebook.Add (this.vbox4);
		global::Gtk.Notebook.NotebookChild w10 = ((global::Gtk.Notebook.NotebookChild)(this.notebook [this.vbox4]));
		w10.Position = 1;
		// Notebook tab
		this.labelCategoria = new global::Gtk.Label ();
		this.labelCategoria.Name = "labelCategoria";
		this.labelCategoria.LabelProp = global::Mono.Unix.Catalog.GetString ("Categoría");
		this.notebook.SetTabLabel (this.vbox4, this.labelCategoria);
		this.labelCategoria.ShowAll ();
		this.vbox1.Add (this.notebook);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook]));
		w11.Position = 1;
		this.GtkAlignment.Add (this.vbox1);
		this.frame1.Add (this.GtkAlignment);
		this.frame = new global::Gtk.Label ();
		this.frame.Name = "frame";
		this.frame.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Gestión</b>");
		this.frame.UseMarkup = true;
		this.frame1.LabelWidget = this.frame;
		this.Add (this.frame1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 271;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.newActionArticulo.Activated += new global::System.EventHandler (this.OnNewActionArticuloActivated);
		this.newActionCategoria.Activated += new global::System.EventHandler (this.OnNewActionCategoriaActivated);
	}
}
